### ISSUE TITLE
Wrong URL in RUN

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [Swagger2Markup/swagger2markup-image#2]
Hello,

i think the correct RUN command should be:

`RUN ... wget https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.1/swagger2markup-cli-1.3.1.jar`

`1.3.1` not `1.3.0`

**Comment by RobWin** [comment]
Thx

**Comment by MennoVS** [comment]
Could you upload it to Docker Hub? As a temporary fix I've uploaded an updated version on https://hub.docker.com/r/mvstarrenburg/swagger2markup/

**Comment by RobWin** [comment]
Done. https://hub.docker.com/r/swagger2markup/swagger2markup/tags/
Thanks for the hint.

**Comment by MennoVS** [comment]
Great, thanks! Taking mine down FYI.
